spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
  application:
    name: server-dev
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://47.96.107.184:3306/zhzx-prod?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&allowMultiQueries=true
      username: zxax
      password: zxxb@yy330
    mssql:
      jdbc-url: jdbc:sqlserver://10.100.10.111:1433;DatabaseName=AsiaCardserver
      username: EKT
      password: 1qaz!QAZ
  redis:
    host: 47.96.107.184
    database: 1
    port: 6379
    password: chenghe666666
    timeout: 10000
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 5000
  resources:
    static-locations: classpath:static/templates/
web:
  upload-path: /home/zhzx-server/file/upload
card:
  consume-record: http://10.100.10.114:8080/ascardapi/api/v1/trans
upload:
  SYSTEM_TYPE: LINUX
  BASE_URL: 39.105.20.167
  FTP_PORT: 21
  DOMAIN_URL: http://47.96.107.184:8088
  DOMAIN_URL_FTP: http://39.105.20.167:21
  COMMON_PATH: zhzx/tmg
  USER_NAME: haha
  PASS_WORD: haha
  HOME_DIR_FTP: /home/tomcat-image/webapps
  HOME_DIR: /home/tomcat-image/webapps
# hasor
# 是否开启 Dataway 后台管理界面（必选：默认false）
HASOR_DATAQL_DATAWAY_ADMIN: true

wx:
  appId: wx7eb20e66c3f76593
  chengguo_secret: 5xOeiEC20AA20nuLLJgsA94Ot6fTY5VRGPkRScuV7es
  zhiban_secret: W8nIAcorja8PoD_HohN8f15omjiztkblu4wC3MH4k5c
  course_secret: Vc5Be0HcVB_WiQPFQ2fo6kdjxSnBikdRae5e7JRYpOc
  njzzb_secret: lEj-4etey6vngFpc7KXTWuJ7pmGM6whZc57ZwuBLK_I
  message_appId: wx7eb20e66c3f76593
  mail_list_secret: NrWm7eO8Oi1Ux7Tnw1A-qBAipYhhkHzWEJVeZZ45vhY  #家校通讯录
  message_secret: Ir15A6_SrSYpw565YjJoEKFISSvZvQjR3W257aXEZkk   #家校应用
  bench_secret: pPQDoVyVoLK9QfOmGN497bFHnDQA0TB2mZbwaXh8Yrs
  total_duty_secret: Vypgiw6feMdR06Nz_vhXRzEw0iNq4C9y3Tzved0BPNk
  oauth_secret: Pm2EhhvOCVNieiB-6j310k1DPlGaUPUDcP3pbqsgrBM
  agentId: 1000049
  resp:
    token: j4byZpKL3VMZXC4IcsQClIfcuvf
    encodingAESKey: TRoUnUhPaR8M6qXbkMw6MG95AbsX5uruI2iRjKQYnwA
academic:
  year_one_start: 9-4
  year_two_start: 2-1
xcx:
  expire_time: 86400
  auth_prefix: f1e13ece5c436eba6c98
  request_url: https://dc.njzhzx.net/api/api/app/getUrlScheme/{code}/{module}
  chat_book_url: http://dc.njzhzx.net/api/api/xcxBase/getContacts
  schoolyard_url: http://dc.njzhzx.net/api/api/xcxBase/getSchoolList
  pc_login_code_url: http://dc.njzhzx.net/api/api/app/checkMobile/{name}/{mobile}
  pc_login_cookie_url: http://dc.njzhzx.net/login2Zh
cas:
  ticket_validate_url: http://localhost:18080/cas_overlay_war_exploded/p3/serviceValidate?ticket={0}&service={1}
  log_out_url: http://localhost:18080/cas_overlay_war_exploded/logout
