insert sys_schoolyard (name, faculty) values('建邺区','高中部');
insert sys_academic_year_semester (year, semester, start_time, end_time, is_default) values('2021-2022','Q1',cast('2021-09-01' as datetime),cast('2022-02-10' as datetime),'YES');
insert sys_academic_year_semester (year, semester, start_time, end_time, is_default) values('2021-2022','Q2',cast('2022-02-11' as datetime),cast('2022-08-31' as datetime),'NO');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('语文','NO','YES',150,'chinese');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('数学','NO','YES',150,'math');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('英语','NO','YES',120,'english');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('物理','NO','YES',100,'physics');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('化学','YES','YES',100,'chemistry');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('生物','YES','YES',100,'biology');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('政治','YES','YES',100,'politics');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('地理','YES','YES',100,'geography');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('历史','NO','YES',100,'history');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('音乐','NO','NO',0,'music');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('体育','NO','NO',0,'sports');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('美术','NO','NO',0,'painting');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('技术','NO','NO',0,'technology');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('心理','NO','NO',0,'psychology');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('逻辑与批判性思维','NO','NO',0,'logic');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('班会','NO','NO',0,'class meeting');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('自习','NO','NO',0,'self study');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('考试','NO','NO',0,'examination');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('语文阅读','NO','NO',0,'chinese read');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('数学训练','NO','NO',0,'math train');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('英语口语','NO','NO',0,'english speak');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('体育锻炼','NO','NO',0,'exercise');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('团队活动','NO','NO',0,'group activities');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('校本课程','NO','NO',0,'based curriculum');
insert sys_subject (name,has_weight,is_main,max_score,subject_alias) values('研究性学习','NO','NO',0,'inquiry learning');
insert sys_grade (schoolyard_id, name, academy_ratio_a, academy_ratio_b, academy_ratio_c, academy_ratio_d, academy_ratio_e) values(1,'高一年级',20,20,20,10,30);
insert sys_grade (schoolyard_id, name, academy_ratio_a, academy_ratio_b, academy_ratio_c, academy_ratio_d, academy_ratio_e) values(1,'高二年级',20,20,30,15,15);
insert sys_grade (schoolyard_id, name, academy_ratio_a, academy_ratio_b, academy_ratio_c, academy_ratio_d, academy_ratio_e) values(1,'高三年级',0,0,0,0,0);
insert sys_department (name, principal, parent_id, sort_order) values('校长室','徐飞',0,1);
insert sys_department (name, principal, parent_id, sort_order) values('党委','李兵',0,2);
insert sys_department (name, principal, parent_id, sort_order) values('办公室','陈柳青',0,3);
insert sys_department (name, principal, parent_id, sort_order) values('工会','牛刚',0,4);
insert sys_department (name, principal, parent_id, sort_order) values('督察室','严龙文',0,5);
insert sys_department (name, principal, parent_id, sort_order) values('教务处','张海宁',0,6);
insert sys_department (name, principal, parent_id, sort_order) values('德育处','张业宏',0,7);
insert sys_department (name, principal, parent_id, sort_order) values('教研处','陈义永',0,8);
insert sys_department (name, principal, parent_id, sort_order) values('总务处','陆俊',0,9);
insert sys_department (name, principal, parent_id, sort_order) values('信息中心','姚发权',0,10);
insert sys_department (name, principal, parent_id, sort_order) values('心理健康教育中心','陶德华',0,11);
insert sys_function_department(name,parent_id,sort_order,principal_id) values('部门',0,1,0);
insert sys_function_department(name,parent_id,sort_order,principal_id) values('年级组',0,2,0);
insert sys_function_department(name,parent_id,sort_order,principal_id) values('校长',0,3,1);
insert sys_function_department(name,parent_id,sort_order,principal_id) values('德育处',1,1,1);
insert sys_function_department(name,parent_id,sort_order,principal_id) values('团委',1,2,1);
insert sys_function_department(name,parent_id,sort_order,principal_id) values('心育中心',1,3,1);
insert sys_function_department(name,parent_id,sort_order,principal_id) values('总务处',1,4,1);
insert sys_function_department(name,parent_id,sort_order,principal_id) values('信息中心',1,5,1);
insert sys_function_department(name,parent_id,sort_order,principal_id) values('校办',1,6,1);
update sys_function_department a, sys_function_department b set a.parent_id=b.id where a.parent_id=1 and b.name='部门';
insert sys_function_department(name,parent_id,sort_order,principal_id) values('高一年级组',2,1,1);
insert sys_function_department(name,parent_id,sort_order,principal_id) values('高二年级组',2,2,1);
insert sys_function_department(name,parent_id,sort_order,principal_id) values('高三年级组',2,3,1);
update sys_function_department a, sys_function_department b set a.parent_id=b.id where a.parent_id=2 and b.name='年级组';
insert sys_staff_category(parent_id,name,remark,create_subordinate) values(0,'部门','总部门','YES');
insert sys_label (classify,name) values('YRCG_YJJY','意见建议一');
insert sys_label (classify,name) values('YRCG_OFSJ','偶发事件一');
insert sys_label (classify,name) values('FZDW','江苏省教育厅');
insert sys_label (classify,name) values('FZDW','江苏省电教馆');
insert sys_label (classify,name) values('FZDW','江苏省教科院');
insert sys_label (classify,name) values('FZDW','南京市教育局');
insert sys_label (classify,name) values('FZDW','南京市教研室');
insert sys_label (classify,name) values('FZDW','南京市电教馆');
insert sys_label (classify,name) values('FZDW','南京市教科所');
insert sys_label (classify,name) values('YKHJ_BSMC','优质课评比');
insert sys_label (classify,name) values('YKHJ_BSMC','微课大赛');
insert sys_label (classify,name) values('YKHJ_BSMC','一师一优课');
insert sys_label (classify,name) values('YKHJ_BSMC','网络团队课');
insert sys_label (classify,name) values('GRJS_BSMC','基本功大赛');
insert sys_label (classify,name) values('BZ','发热');
insert sys_label (classify,name) values('BZ','咳嗽');
insert sys_label (classify,name) values('BZ','头痛');
insert sys_label (classify,name) values('BZ','咽痛');
insert sys_label (classify,name) values('BZ','腹泻');
insert sys_label (classify,name) values('BZ','呕吐');
insert sys_label (classify,name) values('BZ','红眼');
insert sys_label (classify,name) values('BZ','皮疹');
insert sys_label (classify,name) values('BZ','其他');
insert sys_label (classify,name) values('JY','在家');
insert sys_label (classify,name) values('JY','门诊');
insert sys_label (classify,name) values('JY','住院');
insert sys_label (classify,name) values('JY','不详');
insert sys_label (classify,name) values('WZXKQ','缺席');
insert sys_label (classify,name) values('WZXKQ','迟到');
insert sys_label (classify,name) values('WZXKQ','中途出入教室');
insert sys_label (classify,name) values('WZXKQ','其他');
insert sys_label (classify,name) values('RCKQ','旷课');
insert sys_label (classify,name) values('RCKQ','病假');
insert sys_label (classify,name) values('RCKQ','事假');
insert sys_label (classify,name) values('RCKQ','迟到');
insert sys_label (classify,name) values('RCKQ','早退');
insert sys_label (classify,name) values('CLAZZ','1班');
insert sys_label (classify,name) values('CLAZZ','2班');
insert sys_label (classify,name) values('CLAZZ','3班');
insert sys_label (classify,name) values('CLAZZ','4班');
insert sys_label (classify,name) values('CLAZZ','5班');
insert sys_label (classify,name) values('CLAZZ','6班');
insert sys_label (classify,name) values('CLAZZ','7班');
insert sys_label (classify,name) values('CLAZZ','8班');
insert sys_label (classify,name) values('CLAZZ','9班');
insert sys_label (classify,name) values('CLAZZ','10班');
insert sys_label (classify,name) values('CLAZZ','11班');
insert sys_label (classify,name) values('CLAZZ','12班');
insert sys_label (classify,name) values('CLAZZ','13班');
insert sys_label (classify,name) values('CLAZZ','14班');
insert sys_label (classify,name) values('CLAZZ','15班');
insert sys_label (classify,name) values('CLAZZ','16班');
insert sys_label (classify,name) values('CLAZZ','17班');
insert sys_label (classify,name) values('CLAZZ','18班');
insert sys_label (classify,name) values('CLAZZ','19班');
insert sys_label (classify,name) values('CLAZZ','20班');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(1,1,'07:25','08:05');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(1,2,'08:15','08:55');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(1,3,'09:30','10:10');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(1,4,'10:20','11:00');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(1,5,'11:15','11:55');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(1,6,'13:50','14:30');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(1,7,'14:40','15:20');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(1,8,'15:30','16:10');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(1,9,'16:20','17:00');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(1,10,'17:05','17:45');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(1,11,'20:00','22:00');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(1,12,'22:00','23:00');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(2,1,'07:25','08:05');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(2,2,'08:15','08:55');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(2,3,'09:30','10:10');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(2,4,'10:20','11:00');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(2,5,'11:10','11:50');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(2,6,'13:50','14:30');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(2,7,'14:40','15:20');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(2,8,'15:30','16:10');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(2,9,'16:20','17:00');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(2,10,'17:05','17:45');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(2,11,'20:00','22:00');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(2,12,'22:00','23:00');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(3,1,'07:25','08:05');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(3,2,'08:15','08:55');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(3,3,'09:30','10:10');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(3,4,'10:20','11:00');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(3,5,'11:05','11:45');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(3,6,'13:50','14:30');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(3,7,'14:40','15:20');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(3,8,'15:30','16:10');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(3,9,'16:20','17:00');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(3,10,'17:05','17:30');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(3,11,'20:00','22:00');
insert sys_course_time (grade_id,sort_order,start_time,end_time) values(3,12,'22:00','23:00');
insert sys_role (name,remark,editor_id,editor_name) values('ROLE_ADMIN','管理员',1,'admin');
insert sys_role (name,remark,editor_id,editor_name) values('ROLE_LEADER_DUTY','值班领导',1,'admin');
insert sys_role (name,remark,editor_id,editor_name) values('ROLE_TEACHER_DUTY','值班老师',1,'admin');
insert sys_role (name,remark,editor_id,editor_name) values('ROLE_STUDENT_DUTY','值班班长',1,'admin');
insert sys_role (name,remark,editor_id,editor_name) values('ROLE_STAFF','教职工',1,'admin');
insert sys_role (name,remark,editor_id,editor_name) values('ROLE_STUDENT','学生',1,'admin');
insert sys_user (username,login_number,password,real_name) values('admin','admin','34be8da3b5eff97e83eeb201624d7080894d037d123572d64a112b3f429ab1294be6e1dfa232597f94d8a549f1dfeb431b9bdce0fe878314002833e9f344b6b4', '管理员');
insert sys_user_role (user_id,role_id) values(1,1);
insert sys_role_authority(role_id,authority_id) select 1,id from sys_authority;
insert sys_settings(code,remark,params) values('CARD','一卡通配置参数','{"printName":"Microsoft Print to PDF", "paper":"A4"}');
insert sys_settings(code,remark,params) values('LARGE','大屏配置参数','{"dayTitle":"新冠疫情防控数据统计"}');
insert sys_settings(code,remark,params) values('MESSAGE_LAST_SEND_TIME','上次发送时间','2020-01-01 00:00:00');
insert sys_settings(code,remark,params) values('MESSAGE_URL','微信发送url','http://192.168.100.111:8000/#/user/formWrite');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('综合表彰',0,1,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('教学类',0,2,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('德育类',0,3,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('个人荣誉',1,1,1,'管理员');
update sys_teaching_result_classify a, sys_teaching_result_classify b set a.parent_id=b.id where a.parent_id=1 and b.name='综合表彰';
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('个人荣誉',2,1,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('集体荣誉',2,2,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('论文发表',2,3,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('论文评比获奖',2,4,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('论著出版',2,5,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('参编教材',2,6,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('课题研究',2,7,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('示范课、研究课开设',2,8,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('优课获奖',2,9,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('讲座开设',2,10,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('个人竞赛获奖',2,11,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('指导学生获奖',2,12,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('指导青年教师',2,13,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('进修培训',2,14,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('微课获奖',2,15,1,'管理员');
update sys_teaching_result_classify a, sys_teaching_result_classify b set a.parent_id=b.id where a.parent_id=2 and b.name='教学类';
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('个人荣誉',3,1,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('班级荣誉',3,2,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('论文发表',3,3,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('论文评比获奖',3,4,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('论著出版',3,5,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('参编教材',3,6,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('课题研究',3,7,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('讲座开设',3,8,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('个人竞赛获奖',3,9,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('指导学生获奖',3,10,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('指导青年教师',3,11,1,'管理员');
insert sys_teaching_result_classify(name,parent_id,sort_order,editor_id,editor_name) values('进修培训',3,13,1,'管理员');
update sys_teaching_result_classify a, sys_teaching_result_classify b set a.parent_id=b.id where a.parent_id=3 and b.name='德育类';
insert sys_teaching_result_declaration_classify(name,parent_id,sort_order,editor_id,editor_name) values('2016教师专业发展评比',0,1,1,'管理员');
insert sys_teaching_result_declaration_classify(name,parent_id,sort_order,editor_id,editor_name) values('2016教科研成果申报',0,2,1,'管理员');
insert sys_teaching_result_declaration_classify(name,parent_id,sort_order,editor_id,editor_name) values('A类（非B类教师）',1,1,1,'管理员');
insert sys_teaching_result_declaration_classify(name,parent_id,sort_order,editor_id,editor_name) values('B1类（入职3年内新教师）',1,2,1,'管理员');
insert sys_teaching_result_declaration_classify(name,parent_id,sort_order,editor_id,editor_name) values('B2类（35岁以下年青教师）',1,3,1,'管理员');
insert sys_teaching_result_declaration_classify(name,parent_id,sort_order,editor_id,editor_name) values('B3类（市青优后备）',1,4,1,'管理员');
insert sys_teaching_result_declaration_classify(name,parent_id,sort_order,editor_id,editor_name) values('B4类（市学带后备）',1,5,1,'管理员');
insert sys_teaching_result_declaration_classify(name,parent_id,sort_order,editor_id,editor_name) values('B5类（省特级后备）',1,6,1,'管理员');
insert sys_teaching_result_declaration_classify(name,parent_id,sort_order,editor_id,editor_name) values('B6类（特级/正高级教师）',1,7,1,'管理员');
update sys_teaching_result_declaration_classify a, sys_teaching_result_declaration_classify b set a.parent_id=b.id where a.parent_id=1 and b.name='2016教师专业发展评比';
insert dat_exam_type (name, weight) values('期中', 30);
insert dat_exam_type (name, weight) values('期末', 40);
insert dat_exam_type (name, weight) values('会考', 0);
insert dat_exam_type (name, weight) values('月考', 20);
insert dat_exam_type (name, weight) values('周考', 10);
